name: Publish

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
          key: release-${{ hashFiles('pyproject.toml') }}

      - run: |
          pip install -U poetry==v1.2.0a2
          poetry config virtualenvs.create false
          poetry plugin add poetry-version-plugin

      - run: poetry install

      - run: poetry build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
