name: Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
          key: test-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}

      - run: |
          pip install -U poetry
          poetry config virtualenvs.create false

      - run: poetry install

      - run: pytest --color=yes --cov
